<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7951" started-at="2019-04-09T12:37:59Z" finished-at="2019-04-09T12:38:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7951" started-at="2019-04-09T12:37:59Z" finished-at="2019-04-09T12:38:07Z">
      <class name="SendEmail.MyTest1WithtestNG2WithTestResult">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:SendEmail.MyTest1WithtestNG2WithTestResult@2ac1fdc4]" name="beforeClass" is-config="true" duration-ms="61" started-at="2019-04-09T18:07:59Z" finished-at="2019-04-09T18:07:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="myTest()[pri:0, instance:SendEmail.MyTest1WithtestNG2WithTestResult@2ac1fdc4]" name="myTest" duration-ms="30" started-at="2019-04-09T18:07:59Z" finished-at="2019-04-09T18:07:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [100] but found [90]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [100] but found [90]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at SendEmail.MyTest1WithtestNG2WithTestResult.myTest(MyTest1WithtestNG2WithTestResult.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myTest -->
        <test-method status="PASS" signature="afterClass(org.testng.ITestResult)[pri:0, instance:SendEmail.MyTest1WithtestNG2WithTestResult@2ac1fdc4]" name="afterClass" is-config="true" duration-ms="7791" started-at="2019-04-09T18:07:59Z" finished-at="2019-04-09T18:08:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=myTest status=FAILURE method=MyTest1WithtestNG2WithTestResult.myTest()[pri:0, instance:SendEmail.MyTest1WithtestNG2WithTestResult@2ac1fdc4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- SendEmail.MyTest1WithtestNG2WithTestResult -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
